# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Testing.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(25, 0, 341, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.InputLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.InputLayout.setContentsMargins(0, 0, 0, 0)
        self.InputLayout.setObjectName("InputLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.InputLayout.addWidget(self.label)
        self.edt_target = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edt_target.setObjectName("edt_target")
        self.InputLayout.addWidget(self.edt_target)
        self.btn_submit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_submit.setObjectName("btn_submit")
        self.InputLayout.addWidget(self.btn_submit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(25, 150, 410, 110))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.WordFinder = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.WordFinder.setContentsMargins(0, 0, 0, 0)
        self.WordFinder.setObjectName("WordFinder")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(420, 0, 221, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_gen1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen1.setEnabled(True)
        self.lbl_gen1.setText("")
        self.lbl_gen1.setObjectName("lbl_gen1")
        self.verticalLayout.addWidget(self.lbl_gen1)
        self.lbl_gen2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen2.setEnabled(True)
        self.lbl_gen2.setText("")
        self.lbl_gen2.setObjectName("lbl_gen2")
        self.verticalLayout.addWidget(self.lbl_gen2)
        self.lbl_gen3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen3.setEnabled(True)
        self.lbl_gen3.setText("")
        self.lbl_gen3.setObjectName("lbl_gen3")
        self.verticalLayout.addWidget(self.lbl_gen3)
        self.lbl_gen4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen4.setEnabled(True)
        self.lbl_gen4.setText("")
        self.lbl_gen4.setObjectName("lbl_gen4")
        self.verticalLayout.addWidget(self.lbl_gen4)
        self.lbl_gen5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen5.setEnabled(True)
        self.lbl_gen5.setText("")
        self.lbl_gen5.setObjectName("lbl_gen5")
        self.verticalLayout.addWidget(self.lbl_gen5)
        self.lbl_gen6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen6.setEnabled(True)
        self.lbl_gen6.setText("")
        self.lbl_gen6.setObjectName("lbl_gen6")
        self.verticalLayout.addWidget(self.lbl_gen6)
        self.lbl_gen7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen7.setEnabled(True)
        self.lbl_gen7.setText("")
        self.lbl_gen7.setObjectName("lbl_gen7")
        self.verticalLayout.addWidget(self.lbl_gen7)
        self.lbl_gen8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen8.setEnabled(True)
        self.lbl_gen8.setText("")
        self.lbl_gen8.setObjectName("lbl_gen8")
        self.verticalLayout.addWidget(self.lbl_gen8)
        self.lbl_gen9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen9.setEnabled(True)
        self.lbl_gen9.setText("")
        self.lbl_gen9.setObjectName("lbl_gen9")
        self.verticalLayout.addWidget(self.lbl_gen9)
        self.lbl_gen10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen10.setEnabled(True)
        self.lbl_gen10.setText("")
        self.lbl_gen10.setObjectName("lbl_gen10")
        self.verticalLayout.addWidget(self.lbl_gen10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Target Word"))
        self.btn_submit.setText(_translate("MainWindow", "Submit"))
