# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Testing.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 0, 341, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.InputLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.InputLayout.setContentsMargins(0, 0, 0, 0)
        self.InputLayout.setObjectName("InputLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.InputLayout.addWidget(self.label)
        self.edt_target = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edt_target.setObjectName("edt_target")
        self.InputLayout.addWidget(self.edt_target)
        self.btn_submit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_submit.setObjectName("btn_submit")
        self.InputLayout.addWidget(self.btn_submit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 410, 110))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.WordFinder = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.WordFinder.setContentsMargins(0, 0, 0, 0)
        self.WordFinder.setObjectName("WordFinder")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(450, 0, 191, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_gen1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen1.setEnabled(True)
        self.lbl_gen1.setText("")
        self.lbl_gen1.setObjectName("lbl_gen1")
        self.verticalLayout.addWidget(self.lbl_gen1)
        self.lbl_gen2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen2.setEnabled(True)
        self.lbl_gen2.setText("")
        self.lbl_gen2.setObjectName("lbl_gen2")
        self.verticalLayout.addWidget(self.lbl_gen2)
        self.lbl_gen3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen3.setEnabled(True)
        self.lbl_gen3.setText("")
        self.lbl_gen3.setObjectName("lbl_gen3")
        self.verticalLayout.addWidget(self.lbl_gen3)
        self.lbl_gen4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen4.setEnabled(True)
        self.lbl_gen4.setText("")
        self.lbl_gen4.setObjectName("lbl_gen4")
        self.verticalLayout.addWidget(self.lbl_gen4)
        self.lbl_gen5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen5.setEnabled(True)
        self.lbl_gen5.setText("")
        self.lbl_gen5.setObjectName("lbl_gen5")
        self.verticalLayout.addWidget(self.lbl_gen5)
        self.lbl_gen6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen6.setEnabled(True)
        self.lbl_gen6.setText("")
        self.lbl_gen6.setObjectName("lbl_gen6")
        self.verticalLayout.addWidget(self.lbl_gen6)
        self.lbl_gen7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen7.setEnabled(True)
        self.lbl_gen7.setText("")
        self.lbl_gen7.setObjectName("lbl_gen7")
        self.verticalLayout.addWidget(self.lbl_gen7)
        self.lbl_gen8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen8.setEnabled(True)
        self.lbl_gen8.setText("")
        self.lbl_gen8.setObjectName("lbl_gen8")
        self.verticalLayout.addWidget(self.lbl_gen8)
        self.lbl_gen9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen9.setEnabled(True)
        self.lbl_gen9.setText("")
        self.lbl_gen9.setObjectName("lbl_gen9")
        self.verticalLayout.addWidget(self.lbl_gen9)
        self.lbl_gen10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_gen10.setEnabled(True)
        self.lbl_gen10.setText("")
        self.lbl_gen10.setObjectName("lbl_gen10")
        self.verticalLayout.addWidget(self.lbl_gen10)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 60, 240, 70))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.sliderLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.sliderLayout.setContentsMargins(0, 0, 0, 0)
        self.sliderLayout.setObjectName("sliderLayout")
        self.PopSlider = QtWidgets.QHBoxLayout()
        self.PopSlider.setObjectName("PopSlider")
        self.lbl_popTitle = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_popTitle.setObjectName("lbl_popTitle")
        self.PopSlider.addWidget(self.lbl_popTitle)
        self.sld_popSize = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.sld_popSize.setMaximum(5000)
        self.sld_popSize.setOrientation(QtCore.Qt.Horizontal)
        self.sld_popSize.setObjectName("sld_popSize")
        self.PopSlider.addWidget(self.sld_popSize)
        self.sliderLayout.addLayout(self.PopSlider)
        self.MutationSlider = QtWidgets.QHBoxLayout()
        self.MutationSlider.setSpacing(14)
        self.MutationSlider.setObjectName("MutationSlider")
        self.lbl_mutTitle = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_mutTitle.setObjectName("lbl_mutTitle")
        self.MutationSlider.addWidget(self.lbl_mutTitle)
        self.sld_mutRate = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.sld_mutRate.setMaximum(100)
        self.sld_mutRate.setSingleStep(1)
        self.sld_mutRate.setOrientation(QtCore.Qt.Horizontal)
        self.sld_mutRate.setObjectName("sld_mutRate")
        self.MutationSlider.addWidget(self.sld_mutRate)
        self.sliderLayout.addLayout(self.MutationSlider)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 320, 229, 56))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_currentGenTitle = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_currentGenTitle.setObjectName("lbl_currentGenTitle")
        self.horizontalLayout.addWidget(self.lbl_currentGenTitle)
        self.lbl_currentGen = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_currentGen.setObjectName("lbl_currentGen")
        self.horizontalLayout.addWidget(self.lbl_currentGen)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_avgFitnessTitle = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_avgFitnessTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_avgFitnessTitle.setObjectName("lbl_avgFitnessTitle")
        self.horizontalLayout_3.addWidget(self.lbl_avgFitnessTitle)
        self.lbl_avgFitness = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_avgFitness.setObjectName("lbl_avgFitness")
        self.horizontalLayout_3.addWidget(self.lbl_avgFitness)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.lbl_popSize = QtWidgets.QLabel(self.centralwidget)
        self.lbl_popSize.setGeometry(QtCore.QRect(270, 60, 68, 29))
        self.lbl_popSize.setObjectName("lbl_popSize")
        self.lbl_mutRate = QtWidgets.QLabel(self.centralwidget)
        self.lbl_mutRate.setGeometry(QtCore.QRect(270, 100, 68, 29))
        self.lbl_mutRate.setObjectName("lbl_mutRate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WordFinder"))
        self.label.setText(_translate("MainWindow", "Target Word"))
        self.btn_submit.setText(_translate("MainWindow", "Submit"))
        self.lbl_popTitle.setText(_translate("MainWindow", "Max Population"))
        self.lbl_mutTitle.setText(_translate("MainWindow", "Mutation Rate"))
        self.lbl_currentGenTitle.setText(_translate("MainWindow", "Generation"))
        self.lbl_currentGen.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_avgFitnessTitle.setText(_translate("MainWindow", "Average Fitness"))
        self.lbl_avgFitness.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_popSize.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_mutRate.setText(_translate("MainWindow", "TextLabel"))
